name: .NET

on: push #So it activates everytime someone makes a commit on either main or any fork (hopefully)
  

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      working-directory: Source
      run: dotnet restore
    - name: Build
      working-directory: Source
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
